# Generated by Django 4.2.5 on 2023-09-15 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_firstname', models.CharField(max_length=20)),
                ('customer_lastname', models.CharField(max_length=20)),
                ('customer_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10-digit phone number.')])),
                ('customer_email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(max_length=3)),
                ('room_floor', models.IntegerField(max_length=2)),
                ('room_category', models.CharField(max_length=1)),
            ],
        ),
    ]
