# Generated by Django 4.2.5 on 2023-09-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_startdate', models.DateField()),
                ('book_enddate', models.DateField()),
                ('book_adults', models.IntegerField()),
                ('book_childs', models.IntegerField()),
                ('book_category', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_floor',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_number',
        ),
    ]
