# Generated by Django 4.2.5 on 2023-09-19 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_book_remove_room_room_floor_remove_room_room_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_firstname',
            new_name='customer_fname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_lastname',
            new_name='customer_lname',
        ),
    ]
